import { StyleSheet } from "react-native";
import { colors, radius, shadow, spacing } from "../../theme";

export const styles = StyleSheet.create({
  titleIcon: {
    borderRadius: radius.md,
    height: 46,
    width: 46,
  },
  gapCard: {
    gap: spacing.md,
    marginBottom: spacing.lg,
  },
  dailyFocusList: {
    gap: spacing.sm,
    marginTop: spacing.xs,
  },
  dailyFocusItem: {
    alignItems: "center",
    backgroundColor: "rgba(0, 92, 174, 0.06)",
    borderRadius: radius.md,
    flexDirection: "row",
    gap: spacing.sm,
    minHeight: 40,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  dailyFocusText: {
    color: colors.text,
    flex: 1,
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 18,
  },
  sectionLabel: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 0.6,
    marginBottom: spacing.sm,
    marginTop: spacing.sm,
    textTransform: "uppercase",
  },
  successText: {
    color: colors.success,
    fontSize: 13,
    fontWeight: "800",
    lineHeight: 19,
  },
  modeBanner: {
    backgroundColor: colors.primary,
    borderColor: "transparent",
    gap: spacing.sm,
    marginBottom: spacing.lg,
  },
  modeBannerTitle: {
    color: colors.onPrimary,
    fontSize: 30,
    fontWeight: "900",
  },
  modeBannerMeta: {
    color: "rgba(255,255,255,0.82)",
    fontSize: 13,
    fontWeight: "700",
  },
  modeActiveTitle: {
    color: colors.text,
    fontSize: 30,
    fontWeight: "900",
  },
  metricRow: {
    flexDirection: "row",
    gap: spacing.md,
    marginBottom: spacing.lg,
  },
  quickGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.md,
  },
  quickButton: {
    flexBasis: "47%",
    flexGrow: 1,
    minHeight: 62,
  },
  listRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.md,
    paddingVertical: spacing.sm,
  },
  listTitle: {
    color: colors.text,
    fontSize: 15,
    fontWeight: "800",
  },
  barRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.md,
    justifyContent: "space-between",
    paddingVertical: spacing.sm,
  },
  barWrap: {
    alignItems: "center",
    flex: 1,
    gap: spacing.sm,
  },
  barTrack: {
    backgroundColor: "rgba(194, 198, 211, 0.22)",
    borderRadius: 999,
    height: 90,
    justifyContent: "flex-end",
    width: 14,
    overflow: "hidden",
  },
  bar: {
    borderRadius: 999,
    width: "100%",
  },
  barLabel: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: "900",
  },
  rowAction: {
    alignItems: "center",
    backgroundColor: colors.surfaceLow,
    borderBottomColor: "rgba(194,198,211,0.24)",
    borderBottomWidth: 1,
    borderRadius: radius.md,
    flexDirection: "row",
    gap: spacing.md,
    marginBottom: spacing.sm,
    minHeight: 70,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
  },
  rowActionPressed: {
    transform: [{ scale: 0.99 }],
  },
  rowIcon: {
    alignItems: "center",
    backgroundColor: colors.primarySoft,
    borderRadius: radius.md,
    height: 42,
    justifyContent: "center",
    width: 42,
  },
  moodRow: {
    flexDirection: "row",
    gap: spacing.sm,
  },
  moodDot: {
    alignItems: "center",
    backgroundColor: colors.surfaceHigh,
    borderColor: "rgba(194,198,211,0.28)",
    borderRadius: radius.md,
    borderWidth: 1,
    flex: 1,
    height: 48,
    justifyContent: "center",
  },
  moodDotActive: {
    backgroundColor: colors.primary,
  },
  moodText: {
    color: colors.text,
    fontWeight: "900",
  },
  moodTextActive: {
    color: colors.onPrimary,
  },
  choiceWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  choice: {
    backgroundColor: colors.surfaceLow,
    borderColor: "rgba(194,198,211,0.28)",
    borderRadius: radius.md,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  choiceActive: {
    backgroundColor: colors.primary,
  },
  choiceText: {
    color: colors.text,
    fontSize: 13,
    fontWeight: "800",
  },
  choiceTextActive: {
    color: colors.onPrimary,
  },
  bullet: {
    color: colors.text,
    fontSize: 14,
    lineHeight: 22,
  },
  taskCard: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: spacing.md,
    marginBottom: spacing.md,
  },
  editingTaskCard: {
    borderColor: colors.primary,
  },
  taskCheck: {
    paddingTop: 2,
  },
  doneText: {
    color: colors.muted,
    textDecorationLine: "line-through",
  },
  badgeRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
    marginTop: spacing.sm,
  },
  iconButton: {
    padding: spacing.sm,
  },
  taskActions: {
    alignItems: "center",
    gap: spacing.xs,
  },
  editForm: {
    gap: spacing.md,
  },
  inlineActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  inlineActionButton: {
    flexGrow: 1,
    minHeight: 44,
  },
  buttonInline: {
    color: colors.onPrimary,
    fontWeight: "900",
  },
  spaceBetween: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.md,
    justifyContent: "space-between",
  },
  progressTrack: {
    backgroundColor: colors.surfaceHigh,
    borderRadius: 999,
    height: 10,
    overflow: "hidden",
  },
  progressFill: {
    backgroundColor: colors.primary,
    height: "100%",
  },
  bigMetric: {
    color: colors.text,
    fontSize: 30,
    fontWeight: "900",
  },
  modeGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.md,
    marginBottom: spacing.lg,
  },
  modeTile: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderColor: "rgba(194,198,211,0.22)",
    borderRadius: radius.lg,
    borderWidth: 1,
    flexBasis: "47%",
    flexGrow: 1,
    minHeight: 86,
    justifyContent: "center",
    ...shadow,
  },
  modeTileText: {
    color: colors.primary,
    fontSize: 15,
    fontWeight: "900",
  },
  statRow: {
    borderBottomColor: "rgba(194,198,211,0.24)",
    borderBottomWidth: 1,
    gap: spacing.xs,
    paddingVertical: spacing.md,
  },
  resourceCard: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: spacing.md,
    marginBottom: spacing.md,
  },
  unreadCard: {
    borderColor: colors.primary,
  },
  profileHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.md,
  },
  avatar: {
    alignItems: "center",
    backgroundColor: colors.primarySoft,
    borderRadius: 999,
    height: 76,
    justifyContent: "center",
    width: 76,
  },
  chatList: {
    flex: 1,
  },
  chatListContent: {
    gap: spacing.md,
    paddingBottom: spacing.md,
  },
  suggestionCard: {
    gap: spacing.md,
    marginTop: spacing.sm,
    shadowOpacity: 0,
  },
  bubble: {
    borderRadius: radius.md,
    maxWidth: "86%",
    padding: spacing.md,
  },
  userBubble: {
    alignSelf: "flex-end",
    backgroundColor: colors.primary,
  },
  assistantBubble: {
    alignSelf: "flex-start",
    backgroundColor: colors.surface,
    borderColor: colors.outline,
    borderWidth: 1,
  },
  userBubbleText: {
    color: colors.onPrimary,
    fontSize: 15,
    lineHeight: 21,
  },
  assistantBubbleText: {
    color: colors.text,
    fontSize: 15,
    lineHeight: 21,
  },
  chatComposer: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderColor: "rgba(194,198,211,0.34)",
    borderRadius: radius.xl,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.sm,
    padding: spacing.sm,
    ...shadow,
  },
  chatInputWrap: {
    alignItems: "center",
    backgroundColor: colors.surfaceLow,
    borderColor: "rgba(194,198,211,0.26)",
    borderRadius: radius.xl,
    borderWidth: 1,
    flex: 1,
    flexDirection: "row",
    minHeight: 54,
    paddingLeft: spacing.sm,
  },
  chatInputWrapRecording: {
    backgroundColor: colors.dangerSoft,
    borderColor: "rgba(179,38,30,0.36)",
  },
  chatInputLeading: {
    marginRight: spacing.sm,
  },
  chatInput: {
    color: colors.text,
    flex: 1,
    fontSize: 14,
    minHeight: 52,
    paddingRight: spacing.md,
  },
  sendButton: {
    alignItems: "center",
    backgroundColor: colors.primary,
    borderRadius: radius.xl,
    height: 54,
    justifyContent: "center",
    width: 54,
  },
  sendButtonDisabled: {
    opacity: 0.45,
  },
  voiceMicButton: {
    backgroundColor: colors.primaryDark,
  },
  voiceStopButton: {
    backgroundColor: colors.danger,
  },
  voiceAssistantBubble: {
    gap: spacing.sm,
  },
  voiceBubbleHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.sm,
  },
  voiceBubbleLabel: {
    color: colors.primary,
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.3,
    textTransform: "uppercase",
  },
  voiceChatStatus: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderColor: "rgba(0,92,174,0.18)",
    borderRadius: radius.xl,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.md,
    marginBottom: spacing.md,
    padding: spacing.md,
  },
  voiceChatStatusTitle: {
    color: colors.text,
    fontSize: 14,
    fontWeight: "900",
  },
  voiceChatStatusSub: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 17,
  },
  voiceCheckinButton: {
    alignItems: "center",
    backgroundColor: colors.primaryDark,
    borderRadius: radius.xl,
    borderColor: "rgba(255,255,255,0.22)",
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.md,
    marginBottom: spacing.lg,
    minHeight: 84,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
  },
  voiceCheckinTitle: {
    color: colors.onPrimary,
    fontSize: 17,
    fontWeight: "900",
  },
  voiceCheckinSub: {
    color: "rgba(255,255,255,0.75)",
    fontSize: 12,
    fontWeight: "700",
    marginTop: 2,
  },
  ritualFormatCard: {
    gap: spacing.md,
    marginBottom: spacing.lg,
  },
  ritualFormatGrid: {
    gap: spacing.md,
    marginTop: spacing.sm,
  },
  ritualFormatOption: {
    backgroundColor: colors.surfaceLow,
    borderColor: "rgba(194,198,211,0.32)",
    borderRadius: radius.xl,
    borderWidth: 1,
    gap: spacing.sm,
    padding: spacing.lg,
  },
  ritualFormatOptionVoice: {
    backgroundColor: colors.primarySoft,
    borderColor: "rgba(0,92,174,0.22)",
  },
  ritualFormatQuizIcon: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    height: 52,
    justifyContent: "center",
    width: 52,
  },
  ritualFormatOptionTitle: {
    color: colors.text,
    fontSize: 17,
    fontWeight: "900",
  },
  ritualFormatOptionSub: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 19,
  },
  voiceBackRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.xs,
    marginBottom: spacing.md,
  },
  voiceBackRowCompact: {
    padding: spacing.xs,
  },
  voiceBackText: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: "800",
  },
  voiceStartHero: {
    alignItems: "center",
    gap: spacing.md,
    paddingVertical: spacing.xl,
  },
  voiceStartTitle: {
    color: colors.text,
    fontSize: 26,
    fontWeight: "900",
    lineHeight: 32,
    textAlign: "center",
  },
  voiceStartSub: {
    color: colors.muted,
    fontSize: 14,
    fontWeight: "700",
    lineHeight: 21,
    textAlign: "center",
  },
  voiceStartOrbWrap: {
    marginVertical: spacing.lg,
  },
  voiceStartTap: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: "800",
  },
  voiceSessionTopBar: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.sm,
    marginBottom: spacing.md,
  },
  voiceSessionTopTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: "900",
  },
  voiceSessionTopSub: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: "700",
  },
  voiceRitualComposer: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.sm,
    marginTop: spacing.sm,
  },
  voiceRecommendationRow: {
    backgroundColor: colors.surfaceLow,
    borderColor: "rgba(194,198,211,0.28)",
    borderRadius: radius.md,
    borderWidth: 1,
    opacity: 0.55,
    padding: spacing.md,
  },
  voiceRecommendationRowActive: {
    borderColor: colors.primary,
    opacity: 1,
  },
  voiceOrbWrap: {
    alignItems: "center",
    justifyContent: "center",
  },
  voiceOrbPulse: {
    borderRadius: 999,
    height: "100%",
    position: "absolute",
    width: "100%",
  },
  voiceOrb: {
    alignItems: "center",
    borderColor: "rgba(255,255,255,0.28)",
    borderRadius: 999,
    borderWidth: 1,
    height: "82%",
    justifyContent: "center",
    width: "82%",
  },
  voiceBars: {
    alignItems: "center",
    flexDirection: "row",
    gap: 5,
    minHeight: 42,
  },
  voiceBar: {
    backgroundColor: colors.primary,
    borderRadius: 999,
    width: 5,
  },
  voiceSessionCard: {
    backgroundColor: colors.surface,
    borderColor: "rgba(0,92,174,0.16)",
    gap: spacing.lg,
    marginBottom: spacing.lg,
  },
  voiceSessionHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.md,
  },
  voiceSessionTitle: {
    color: colors.text,
    fontSize: 24,
    fontWeight: "900",
  },
  voiceSessionSub: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 19,
  },
  voicePeriodSwitch: {
    backgroundColor: colors.surfaceLow,
    borderRadius: radius.lg,
    flexDirection: "row",
    gap: spacing.xs,
    padding: spacing.xs,
  },
  voicePeriodButton: {
    alignItems: "center",
    borderRadius: radius.md,
    flex: 1,
    minHeight: 42,
    justifyContent: "center",
  },
  voicePeriodButtonActive: {
    backgroundColor: colors.primary,
  },
  voicePeriodText: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: "900",
  },
  voicePeriodTextActive: {
    color: colors.onPrimary,
  },
  voicePrimaryAction: {
    minHeight: 52,
  },
  voicePressed: {
    transform: [{ scale: 0.98 }],
  },
  voiceLiveStrip: {
    alignItems: "center",
    backgroundColor: colors.dangerSoft,
    borderColor: "rgba(179,38,30,0.22)",
    borderRadius: radius.lg,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.sm,
    marginBottom: spacing.lg,
    padding: spacing.md,
  },
  voiceLiveText: {
    color: colors.danger,
    fontSize: 13,
    fontWeight: "900",
  },
  voiceQuestionCard: {
    gap: spacing.md,
    marginBottom: spacing.lg,
  },
  voiceQuestionCardActive: {
    borderColor: colors.danger,
  },
  voiceCurrentRecorder: {
    alignItems: "center",
    backgroundColor: colors.surfaceLow,
    borderColor: "rgba(0,92,174,0.14)",
    borderRadius: radius.xl,
    borderWidth: 1,
    gap: spacing.sm,
    padding: spacing.lg,
  },
  voiceMainRecordButton: {
    alignItems: "center",
    justifyContent: "center",
  },
  voiceMainRecordButtonActive: {
    transform: [{ scale: 1.02 }],
  },
  voiceCurrentActionText: {
    color: colors.text,
    fontSize: 17,
    fontWeight: "900",
    marginTop: spacing.sm,
  },
  voiceCurrentHint: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 18,
    textAlign: "center",
  },
  voiceCurrentTranscript: {
    backgroundColor: colors.surfaceLow,
    borderColor: "rgba(194,198,211,0.24)",
    borderRadius: radius.lg,
    borderWidth: 1,
    gap: spacing.xs,
    padding: spacing.md,
  },
  voiceQuestionHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.md,
  },
  voiceQuestionNumber: {
    alignItems: "center",
    backgroundColor: colors.primarySoft,
    borderRadius: radius.md,
    height: 38,
    justifyContent: "center",
    width: 38,
  },
  voiceQuestionNumberText: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: "900",
  },
  voiceQuestionTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: "900",
    lineHeight: 22,
  },
  voiceQuestionMeta: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: "800",
    marginTop: 2,
  },
  voiceTranscriptInput: {
    backgroundColor: colors.surfaceLow,
    minHeight: 94,
    textAlignVertical: "top",
  },
  voiceRecordButton: {
    alignItems: "center",
    backgroundColor: colors.surfaceLow,
    borderColor: "rgba(0,92,174,0.18)",
    borderRadius: radius.lg,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.md,
    minHeight: 72,
    padding: spacing.md,
  },
  voiceRecordButtonActive: {
    backgroundColor: colors.danger,
    borderColor: colors.danger,
  },
  voiceRecordTitle: {
    color: colors.text,
    fontSize: 14,
    fontWeight: "900",
  },
  voiceRecordTitleActive: {
    color: colors.onPrimary,
  },
  voiceRecordSub: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 17,
    marginTop: 2,
  },
  voiceRecordSubActive: {
    color: "rgba(255,255,255,0.78)",
  },
  voiceAnalysisCard: {
    gap: spacing.md,
    marginBottom: spacing.lg,
  },
  voiceTranscriptStack: {
    gap: spacing.md,
    marginBottom: spacing.lg,
  },
  voiceTranscriptRow: {
    alignItems: "center",
    backgroundColor: colors.surfaceLow,
    borderColor: "rgba(194,198,211,0.18)",
    borderRadius: radius.lg,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.md,
    minHeight: 72,
    padding: spacing.md,
  },
  voiceTranscriptRowActive: {
    backgroundColor: colors.accentSoft,
    borderColor: "rgba(0,92,174,0.22)",
  },
  voiceTranscriptQuestion: {
    color: colors.text,
    fontSize: 13,
    fontWeight: "900",
  },
  voiceTranscriptPreview: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 17,
    marginTop: 2,
  },
  ritualHero: {
    backgroundColor: colors.primaryDark,
    borderColor: "rgba(255,255,255,0.18)",
    gap: spacing.lg,
    marginBottom: spacing.lg,
    overflow: "hidden",
  },
  ritualHeroTop: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.md,
  },
  ritualHeroMark: {
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.16)",
    borderColor: "rgba(255,255,255,0.24)",
    borderRadius: radius.lg,
    borderWidth: 1,
    height: 48,
    justifyContent: "center",
    width: 48,
  },
  ritualHeroEyebrow: {
    color: "rgba(255,255,255,0.68)",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  ritualHeroTitle: {
    color: colors.onPrimary,
    fontSize: 25,
    fontWeight: "900",
    lineHeight: 31,
  },
  ritualProgressTrack: {
    backgroundColor: "rgba(255,255,255,0.18)",
    borderRadius: 999,
    height: 10,
    overflow: "hidden",
  },
  ritualProgressFill: {
    backgroundColor: colors.onPrimary,
    borderRadius: 999,
    height: "100%",
  },
  ritualHeroMetrics: {
    flexDirection: "row",
    gap: spacing.sm,
  },
  ritualHeroMetric: {
    backgroundColor: "rgba(255,255,255,0.12)",
    borderColor: "rgba(255,255,255,0.16)",
    borderRadius: radius.md,
    borderWidth: 1,
    flex: 1,
    minHeight: 66,
    padding: spacing.sm,
  },
  ritualHeroMetricLabel: {
    color: "rgba(255,255,255,0.68)",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 0.3,
    textTransform: "uppercase",
  },
  ritualHeroMetricValue: {
    color: colors.onPrimary,
    fontSize: 18,
    fontWeight: "900",
    marginTop: spacing.xs,
  },
  ritualVoicePanel: {
    alignItems: "center",
    backgroundColor: colors.primary,
    borderColor: "rgba(255,255,255,0.22)",
    borderRadius: radius.xl,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.md,
    marginBottom: spacing.lg,
    minHeight: 118,
    padding: spacing.lg,
    ...shadow,
  },
  ritualVoiceLeft: {
    alignItems: "center",
    gap: spacing.xs,
  },
  ritualVoiceTitle: {
    color: colors.onPrimary,
    fontSize: 21,
    fontWeight: "900",
    lineHeight: 26,
  },
  ritualVoiceSub: {
    color: "rgba(255,255,255,0.78)",
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 18,
    marginTop: spacing.xs,
  },
  ritualPath: {
    gap: spacing.md,
    marginBottom: spacing.lg,
  },
  ritualStepCard: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderColor: "rgba(194,198,211,0.26)",
    borderRadius: radius.xl,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.md,
    minHeight: 84,
    padding: spacing.md,
    ...shadow,
  },
  ritualStepCardDone: {
    backgroundColor: colors.successSoft,
    borderColor: "rgba(5,150,105,0.24)",
  },
  ritualStepIcon: {
    alignItems: "center",
    backgroundColor: colors.primarySoft,
    borderRadius: radius.lg,
    height: 48,
    justifyContent: "center",
    width: 48,
  },
  ritualStepIconDone: {
    backgroundColor: colors.surface,
  },
  ritualStepTitle: {
    color: colors.text,
    fontSize: 17,
    fontWeight: "900",
  },
  ritualStepSub: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 17,
    marginTop: 2,
  },
  ritualCountdownRow: {
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
    marginTop: spacing.sm,
  },
  ritualCountdownLabel: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: "800",
  },
  ritualCountdownValue: {
    color: colors.primary,
    fontSize: 12,
    fontVariant: ["tabular-nums"],
    fontWeight: "900",
    letterSpacing: 0.4,
  },
  handsFreeChip: {
    alignSelf: "flex-start",
    backgroundColor: colors.surfaceLow,
    borderColor: "rgba(194,198,211,0.32)",
    borderRadius: radius.xl,
    borderWidth: 1,
    marginBottom: spacing.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  handsFreeChipActive: {
    backgroundColor: colors.primarySoft,
    borderColor: "rgba(0,92,174,0.28)",
  },
  handsFreeChipText: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: "900",
  },
  handsFreeChipTextActive: {
    color: colors.primary,
  },
  ritualInsightCard: {
    gap: spacing.md,
    marginBottom: spacing.lg,
  },
  ritualPriorityRow: {
    alignItems: "flex-start",
    borderTopColor: "rgba(194,198,211,0.22)",
    borderTopWidth: 1,
    flexDirection: "row",
    gap: spacing.md,
    paddingTop: spacing.md,
  },
  ritualPriorityIndex: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: "900",
    lineHeight: 22,
    width: 22,
  },
  ritualPriorityText: {
    color: colors.text,
    flex: 1,
    fontSize: 14,
    fontWeight: "700",
    lineHeight: 22,
  },
  ritualContextCard: {
    gap: spacing.md,
    marginBottom: spacing.lg,
    shadowOpacity: 0,
  },
  ritualContextRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.md,
  },
  ritualContextTitle: {
    color: colors.text,
    fontSize: 15,
    fontWeight: "900",
    marginBottom: 2,
  },
  checkinRow: {
    flexDirection: "row",
    gap: spacing.md,
  },
  checkinCard: {
    alignItems: "center",
    backgroundColor: colors.surfaceLow,
    borderColor: "rgba(194,198,211,0.28)",
    borderRadius: radius.lg,
    borderWidth: 1,
    flex: 1,
    gap: spacing.sm,
    minHeight: 110,
    justifyContent: "center",
    paddingVertical: spacing.lg,
  },
  checkinCardDone: {
    backgroundColor: colors.successSoft,
    borderColor: colors.success,
  },
  checkinCardTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: "900",
  },
  // ── Recording indicator ──
  recordingIndicator: {
    alignItems: "center",
    backgroundColor: colors.dangerSoft,
    borderColor: colors.danger,
    borderRadius: radius.lg,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.sm,
    marginBottom: spacing.md,
    padding: spacing.md,
  },
  recordingDot: {
    backgroundColor: colors.danger,
    borderRadius: 999,
    height: 10,
    width: 10,
  },
  recordingText: {
    color: colors.danger,
    fontSize: 13,
    fontWeight: "800",
  },
});
