import { StyleSheet } from "react-native";
import { colors, radius, shadow, spacing } from "../../../theme";

export const checkinStyles = StyleSheet.create({
  backRow: {
    alignItems: "center",
    alignSelf: "flex-start",
    flexDirection: "row",
    gap: 4,
    marginBottom: spacing.lg,
  },
  backText: {
    color: colors.muted,
    fontSize: 15,
    fontWeight: "600",
  },
  periodLabel: {
    color: colors.primary,
    fontSize: 13,
    fontWeight: "700",
    letterSpacing: 0.2,
    marginBottom: spacing.xs,
  },
  greeting: {
    color: colors.text,
    fontSize: 28,
    fontWeight: "800",
    letterSpacing: -0.6,
    lineHeight: 34,
  },
  stepHint: {
    color: colors.muted,
    fontSize: 15,
    lineHeight: 22,
    marginTop: spacing.sm,
  },
  progressMeta: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: "600",
    marginBottom: spacing.sm,
  },
  progressTrack: {
    backgroundColor: colors.surfaceHigh,
    borderRadius: 999,
    height: 4,
    marginBottom: spacing.xl,
    overflow: "hidden",
  },
  progressFill: {
    backgroundColor: colors.primary,
    borderRadius: 999,
    height: 4,
  },
  surface: {
    backgroundColor: colors.surface,
    borderColor: "rgba(194,198,211,0.22)",
    borderRadius: radius.xl,
    borderWidth: 1,
    padding: spacing.lg,
    ...shadow,
  },
  formatGroup: {
    gap: 0,
    overflow: "hidden",
  },
  formatRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.md,
    minHeight: 76,
    paddingVertical: spacing.md,
  },
  formatRowBorder: {
    borderBottomColor: "rgba(194,198,211,0.22)",
    borderBottomWidth: 1,
  },
  formatIcon: {
    alignItems: "center",
    backgroundColor: colors.primarySoft,
    borderRadius: radius.lg,
    height: 48,
    justifyContent: "center",
    width: 48,
  },
  formatTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: "700",
  },
  formatSub: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 18,
    marginTop: 2,
  },
  formatChevron: {
    color: colors.outline,
    fontSize: 22,
    fontWeight: "300",
  },
  questionText: {
    color: colors.text,
    fontSize: 20,
    fontWeight: "700",
    letterSpacing: -0.3,
    lineHeight: 28,
    marginBottom: spacing.lg,
  },
  sourcePill: {
    alignSelf: "flex-start",
    backgroundColor: colors.primarySoft,
    borderRadius: 999,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginBottom: spacing.lg,
    paddingHorizontal: spacing.sm + 2,
    paddingVertical: 4,
  },
  sourcePillText: {
    color: colors.primary,
    fontSize: 11,
    fontWeight: "700",
  },
  scaleWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
    justifyContent: "center",
  },
  scaleChip: {
    alignItems: "center",
    backgroundColor: colors.surfaceLow,
    borderColor: "rgba(194,198,211,0.28)",
    borderRadius: radius.lg,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 44,
    minWidth: 44,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
  },
  scaleChipActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  scaleChipText: {
    color: colors.text,
    fontSize: 14,
    fontWeight: "700",
    textAlign: "center",
  },
  scaleChipTextActive: {
    color: colors.onPrimary,
  },
  optionList: {
    gap: spacing.sm,
  },
  optionTile: {
    backgroundColor: colors.surfaceLow,
    borderColor: "rgba(194,198,211,0.28)",
    borderRadius: radius.lg,
    borderWidth: 1,
    minHeight: 48,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
  },
  optionTileActive: {
    backgroundColor: colors.primarySoft,
    borderColor: colors.primary,
  },
  optionTileText: {
    color: colors.text,
    flexShrink: 1,
    fontSize: 15,
    fontWeight: "600",
    lineHeight: 21,
  },
  optionTileTextActive: {
    color: colors.primaryDark,
    fontWeight: "700",
  },
  formFooter: {
    borderTopColor: "rgba(194,198,211,0.22)",
    borderTopWidth: 1,
    gap: spacing.sm,
    marginTop: spacing.xl,
    paddingTop: spacing.lg,
  },
  linkBtn: {
    alignItems: "center",
    paddingVertical: spacing.sm,
  },
  linkBtnText: {
    color: colors.muted,
    fontSize: 14,
    fontWeight: "600",
  },
  resultHero: {
    alignItems: "center",
    marginBottom: spacing.xl,
  },
  resultIcon: {
    alignItems: "center",
    backgroundColor: colors.successSoft,
    borderRadius: 999,
    height: 64,
    justifyContent: "center",
    marginBottom: spacing.md,
    width: 64,
  },
  resultTitle: {
    color: colors.text,
    fontSize: 24,
    fontWeight: "800",
    letterSpacing: -0.4,
    marginBottom: spacing.xs,
  },
  resultSub: {
    color: colors.muted,
    fontSize: 15,
    textAlign: "center",
  },
  summaryBlock: {
    backgroundColor: colors.surfaceLow,
    borderRadius: radius.lg,
    marginBottom: spacing.lg,
    padding: spacing.lg,
  },
  summaryLabel: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.4,
    marginBottom: spacing.sm,
    textTransform: "uppercase",
  },
  summaryText: {
    color: colors.text,
    fontSize: 15,
    lineHeight: 24,
  },
});
