"""Add advanced resource fields

Revision ID: 2f423f6aa8ab
Revises: 6c4e31bbd1aa
Create Date: 2026-04-12 14:33:26.287771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f423f6aa8ab'
down_revision: Union[str, None] = '6c4e31bbd1aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wellbeing_resource', sa.Column('description', sa.String(), nullable=True))
    op.add_column('wellbeing_resource', sa.Column('category', sa.String(), nullable=True))
    op.execute("UPDATE wellbeing_resource SET category = 'General'")
    op.alter_column('wellbeing_resource', 'category', nullable=False)
    op.add_column('wellbeing_resource', sa.Column('ai_instruction', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wellbeing_resource', 'ai_instruction')
    op.drop_column('wellbeing_resource', 'category')
    op.drop_column('wellbeing_resource', 'description')
    # ### end Alembic commands ###
