"""advanced ritual checkins

Revision ID: 4557bb1440f7
Revises: cd30fedc8168
Create Date: 2026-04-12 16:26:26.760838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4557bb1440f7'
down_revision: Union[str, None] = 'cd30fedc8168'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evening_checkin', sa.Column('mode', sa.String(), nullable=False, server_default='qcm'))
    op.add_column('evening_checkin', sa.Column('executive_summary', sa.Text(), nullable=True))
    op.add_column('evening_checkin', sa.Column('detailed_action_plan', sa.JSON(), nullable=True))
    op.add_column('evening_checkin', sa.Column('detected_risks', sa.JSON(), nullable=True))
    op.add_column('morning_checkin', sa.Column('mode', sa.String(), nullable=False, server_default='qcm'))
    op.add_column('morning_checkin', sa.Column('executive_summary', sa.Text(), nullable=True))
    op.add_column('morning_checkin', sa.Column('detailed_action_plan', sa.JSON(), nullable=True))
    op.add_column('morning_checkin', sa.Column('detected_risks', sa.JSON(), nullable=True))
    op.alter_column('evening_checkin', 'mode', server_default=None)
    op.alter_column('morning_checkin', 'mode', server_default=None)
    op.drop_column('morning_checkin', 'generated_plan')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('morning_checkin', sa.Column('generated_plan', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('morning_checkin', 'detected_risks')
    op.drop_column('morning_checkin', 'detailed_action_plan')
    op.drop_column('morning_checkin', 'executive_summary')
    op.drop_column('morning_checkin', 'mode')
    op.drop_column('evening_checkin', 'detected_risks')
    op.drop_column('evening_checkin', 'detailed_action_plan')
    op.drop_column('evening_checkin', 'executive_summary')
    op.drop_column('evening_checkin', 'mode')
    # ### end Alembic commands ###
