"""Add school verification fields

Revision ID: cd30fedc8168
Revises: 2f423f6aa8ab
Create Date: 2026-04-12 14:49:18.302999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd30fedc8168'
down_revision: Union[str, None] = '2f423f6aa8ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school', sa.Column('official_identifier', sa.String(), nullable=True))
    op.add_column('school', sa.Column('contact_phone', sa.String(), nullable=True))
    op.add_column('school', sa.Column('verification_status', sa.String(), nullable=True))
    op.execute("UPDATE school SET verification_status = 'VERIFIED'")
    op.alter_column('school', 'verification_status', nullable=False)
    op.add_column('school', sa.Column('verification_note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school', 'verification_note')
    op.drop_column('school', 'verification_status')
    op.drop_column('school', 'contact_phone')
    op.drop_column('school', 'official_identifier')
    # ### end Alembic commands ###
